### ISSUE TITLE
cannot optimize `scale14` with DoubleExponential

### ISSUE THREAD

**Issue by pavankum** [openforcefield/smirnoff-plugins#36]
Attached a minimal FB input for reproducing the case. I can optimize `scale14` in regular vdW non-bonded FF (Sage) but not with the DoubleExponential functional form. Edit: The gradient is always zero with DoubleExponential form for scale14.

The following additions to the file [handlers/nonbonded.py](https://github.com/openforcefield/smirnoff-plugins/blob/main/smirnoff_plugins/handlers/nonbonded.py#L389) fixed it, I don't know if both the changes are needed or just adding the parameter attribute is enough
```
at line397: scale14 = ParameterAttribute(default=0.5)
at line453: global_parameters = ["alpha", "beta", "scale14"]

```

[dexp-opt-scale14.tar.gz](https://github.com/openforcefield/smirnoff-plugins/files/9271162/dexp-opt-scale14.tar.gz)

cc: @jthorton @j-wags

**Comment by mattwthompson** [comment]
I would be curious if you only needed to add it to `global_parameters`; it seems like it should already be a `ParameterAttribute` by nature of importing from `CustomNonbondedHandler`?

https://github.com/openforcefield/smirnoff-plugins/blob/b7d8856ef09e47e7253aca6429b5184671fbaccb/smirnoff_plugins/handlers/nonbonded.py#L20-L26

**Comment by pavankum** [comment]
Thank you @mattwthompson. Yeap, that works by just adding to global parameters list.

**Comment by mattwthompson** [comment]
Could you open a PR that includes this change? I don't know how to the best behavior of it, though.

**Comment by pavankum** [comment]
Yeah, just made the PR, will close this issue then.
