### ISSUE TITLE
Changing cutoff length does not work

### ISSUE THREAD

**Issue by jthorton** [openforcefield/smirnoff-plugins#7]
I have been trying to reproduce the published data by [Rowley](https://doi.org/10.1063/5.0014469) on the Buckingham-68 water model. When using the water offxml generated in the example script the simulation crashes due to the periodic box size decreasing to less than twice the nonbonded cutoff. I think this is due to differences in the nonbonded cutoff lengths, by default FB uses 8.5 angstrom which works with the input water given in the above study however the openff default is 9 angstroms. Changing the cutoff in the Buckingham-68 offxml however, causes an error in OpenMM as all forces in the nonbonded force group do not have the same cutoff distance. This must mean that the either a cutoff is hard coded somewhere in the toolkit or the plugins and is not being changed in line with the options in the offxml.

**Comment by mattwthompson** [comment]
I think this has been fixed for a while, but double-checking after #53:


```python
import openmm
import openmm.unit
from openff.toolkit import ForceField, Molecule
from openff.units import unit


def get_cutoff(force_field, topology) -> float:
    system = force_field.create_interchange(topology).to_openmm(
        combine_nonbonded_forces=False
    )
    for force in system.getForces():
        if isinstance(force, (openmm.NonbondedForce, openmm.CustomNonbondedForce)):
            print(force.getCutoffDistance().value_in_unit(openmm.unit.nanometer))


force_field = ForceField("new/de-force-1.0.0.offxml", load_plugins=True)
# Important!
force_field.deregister_parameter_handler("vdW")

topology = Molecule.from_smiles("O").to_topology()
topology.box_vectors = unit.Quantity([5, 5, 5], unit.nanometer)

get_cutoff(force_field, topology)
# 0.9
# 0.9

force_field["DoubleExponential"].cutoff *= 1.2 / 0.9

get_cutoff(force_field, topology)
# 1.2
# 1.2
